#!/bin/sh

test -d /tmp/HochobMediaSource/ && echo "Directory exists" || mkdir /tmp/HochobMediaSource/

# Hochob Server Media

export HOCHOB_SERVER_MEDIA=$HOME/HochobServerMedia/

export HOCHOB_SERVER_MEDIA_AREA=$HOCHOB_SERVER_MEDIA/Area/
export HOCHOB_SERVER_MEDIA_AREA_SOUTERN_MAYA_HIGHLANDS=$HOCHOB_SERVER_MEDIA_AREA/SouthernMayaHighlands
export HOCHOB_SERVER_MEDIA_AREA_CENTRAL_MAYA_LOWLANDS=$HOCHOB_SERVER_MEDIA_AREA/CentralMayaLowlands
export HOCHOB_SERVER_MEDIA_AREA_NORTHERN_MAYA_LOWLANDS=$HOCHOB_SERVER_MEDIA_AREA/NorthernMayaLowlands

export HOCHOB_SERVER_MEDIA_MEMORIES=$HOCHOB_SERVER_MEDIA/Memories/
export HOCHOB_SERVER_MEDIA_MEMORIES_AMIKOO=$HOCHOB_SERVER_MEDIA_MEMORIES/Amikoo/
export HOCHOB_SERVER_MEDIA_MEMORIES_CAMERA=$HOCHOB_SERVER_MEDIA_MEMORIES/Camera/
export HOCHOB_SERVER_MEDIA_MEMORIES_DRAWING=$HOCHOB_SERVER_MEDIA_MEMORIES/Drawing/
export HOCHOB_SERVER_MEDIA_MEMORIES_VIDEO=$HOCHOB_SERVER_MEDIA_MEMORIES/Video/

export HOCHOB_SERVER_MEDIA_TRADITION=$HOCHOB_SERVER_MEDIA/Tradition/

export HOCHOB_SERVER_MEDIA_VISITORS=$HOCHOB_SERVER_MEDIA/Visitors/

test -d $HOCHOB_SERVER_MEDIA && echo "Directory exists" || mkdir $HOCHOB_SERVER_MEDIA

test -d $HOCHOB_SERVER_MEDIA_AREA && echo "Directory exists" || mkdir $HOCHOB_SERVER_MEDIA_AREA
test -d $HOCHOB_SERVER_MEDIA_AREA_SOUTERN_MAYA_HIGHLANDS && echo "Directory exists" || mkdir $HOCHOB_SERVER_MEDIA_AREA_SOUTERN_MAYA_HIGHLANDS
test -d $HOCHOB_SERVER_MEDIA_AREA_CENTRAL_MAYA_LOWLANDS && echo "Directory exists" || mkdir $HOCHOB_SERVER_MEDIA_AREA_CENTRAL_MAYA_LOWLANDS
test -d $HOCHOB_SERVER_MEDIA_AREA_NORTHERN_MAYA_LOWLANDS && echo "Directory exists" || mkdir $HOCHOB_SERVER_MEDIA_AREA_NORTHERN_MAYA_LOWLANDS

test -d $HOCHOB_SERVER_MEDIA_MEMORIES && echo "Directory exists" || mkdir $HOCHOB_SERVER_MEDIA_MEMORIES
test -d $HOCHOB_SERVER_MEDIA_MEMORIES_CAMERA && echo "Directory exists" || mkdir $HOCHOB_SERVER_MEDIA_MEMORIES_CAMERA
test -d $HOCHOB_SERVER_MEDIA_MEMORIES_DRAWING && echo "Directory exists" || mkdir $HOCHOB_SERVER_MEDIA_MEMORIES_DRAWING
test -d $HOCHOB_SERVER_MEDIA_MEMORIES_AMIKOO && echo "Directory exists" || mkdir $HOCHOB_SERVER_MEDIA_MEMORIES_AMIKOO
test -d $HOCHOB_SERVER_MEDIA_MEMORIES_VIDEO && echo "Directory exists" || mkdir $HOCHOB_SERVER_MEDIA_MEMORIES_VIDEO

test -d $HOCHOB_SERVER_MEDIA_TRADITION && echo "Directory exists" || mkdir $HOCHOB_SERVER_MEDIA_TRADITION

test -d $HOCHOB_SERVER_MEDIA_VISITORS && echo "Directory exists" || mkdir $HOCHOB_SERVER_MEDIA_VISITORS

# End of File
