#!/bin/sh

# Hochob Server Configuration

export HOCHOB_SERVER_CONFIGURATION=/tmp/hochob/
export HOCHOB_SERVER_CONFIGURATION_PID=$HOCHOB_SERVER_CONFIGURATION/pid/

test -d $HOCHOB_SERVER_CONFIGURATION || mkdir -p $HOCHOB_SERVER_CONFIGURATION
test -d $HOCHOB_SERVER_CONFIGURATION_PID || mkdir -p $HOCHOB_SERVER_CONFIGURATION_PID

export HOCHOB_SERVER_CONFIGURATION_DEMO=$HOCHOB_SERVER_CONFIGURATION/demo
export HOCHOB_SERVER_CONFIGURATION_LANGUAGE=$HOCHOB_SERVER_CONFIGURATION/language

echo 0 > $HOCHOB_SERVER_CONFIGURATION_DEMO
echo spanish > $HOCHOB_SERVER_CONFIGURATION_LANGUAGE

# End of File
