homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 20.7167
  longitude: -103.4
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 1551
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Mexico_City
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

mqtt:
  broker: iot.eclipse.org
  port: 1883
  client_id: CochinitaPibil
  keepalive: 60

binary_sensor: !include binarysensors.yaml
group: !include groups.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
