homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 20.6208618
  longitude: -103.4254426
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 1579
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Mexico_City
  customize:

   # Entrance

   script.welcome:
    friendly_name: Welcome to Intel Visitor Center
    icon: mdi:human-child
   script.selfie:
    friendly_name: Selfie Record
    icon: mdi:camera
   switch.lupe:
    friendly_name: Lupe Robot Show
    icon: mdi:video

   # Idle

   switch.preview:
    friendly_name: Selfie Preview
    icon: mdi:video
   switch.latest:
    friendly_name: Selfie Play Latest
    icon: mdi:video
   switch.loop:
    friendly_name: Selfie Play All In A Loop
    icon: mdi:video

   # Your Technical Corner

   script.help:
    friendly_name: Visitor Center Needs Technical Help
    icon: mdi:block-helper

   # Hidden

   media_player.main:
    hidden: yes
   automation.lupe_robot_text_to_speech:
    hidden: yes
   automation.lupe_robot_telegram:
    hidden: yes

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
#sun:

#group: !include groups.yaml

# Text to speech
tts:
  platform: google
  #cache: true
  #cache_dir: /tmp/tts
  #time_memory: 300

#sensor:
#  - platform: plex
#  - platform: yr

script:
  welcome:
    alias: Welcome
    sequence:
      - alias: Warm Up
        service: tts.google_say
        data:
          message: "..."
          language: 'es'
      - alias: Welcome To Intel Visitor Center
        service: tts.google_say
        data:
          message: "Bienvenidos a Intel Guadalajara! Buscaremos que Jesus Palomino les de la Bienvenida por medio de un Video"
          language: 'es'
  selfie:
    alias: Selfie
    sequence:
      - alias: Selfie Record
        service: shell_command.selfie
  help:
    alias: Help Needed
    sequence:
      - alias: Hocho Bot Notification
        service: notify.telegram
        data:
          message: "Visitor Center needs technical help!"

shell_command:
  restart_ha: sudo systemctl restart home-assistant.service &
  selfie: python /home/hochob/CodeLabs/Hochob/Photography/selfie.py &

switch:
  platform: command_line
  switches:
    lupe:
      #command_on: "cvlc --no-video-title-show --fullscreen /home/hochob/Videos/BigBuckBunny.mp4 vlc://quit &"
      command_on: "/home/hochob/CodeLabs/Hochob/LupeRobot/Show/LupeRobot720p.sh &"
      command_off: "/home/hochob/CodeLabs/Hochob/LupeRobot/Show/LupeRobotKill.sh"
    preview:
      command_on: "cvlc --no-video-title-show --fullscreen v4l2:///dev/video0"
      command_off: "pkill vlc"
    latest:
      command_on: "cvlc --no-video-title-show --fullscreen /home/hochob/Selfies/latest.mp4"
      command_off: "pkill vlc"
    loop:
      command_on: "cvlc --no-video-title-show --fullscreen --loop /home/hochob/Selfies/*.mp4"
      command_off: "pkill vlc"

media_player:
  - platform: vlc
    name: main
#  - platform: plex
#  - platform: cast
#  - platform: kodi
#    host: 127.0.0.1
#    user: kodi
#    password: kodi

notify:
  - platform: telegram
    name: telegram
    api_key: 301796470:AAHTZ7pYgjqVwOAzBDIIHfGziMvCrIFc_co
    chat_id: 166426424

automation:
#  - alias: Lupe Robot Text To Speech
#    hide_entity: True
#    trigger:
#      platform: state
#      entity_id: switch.lupe
#      state: 'on'
#    action:
#      service: tts.google_say
#      data:
#        message: "Bienvenido Robot Lupe"
#        language: 'es'
  - alias: Lupe Robot Telegram
    hide_entity: True
    trigger:
      platform: state
      entity_id: switch.lupe
      state: 'on'
    action:
      service: notify.telegram
      data:
        message: "Lupe Robot Station has been activated"

group:
  entrance:
    name: Welcome Center
    entities:
    - script.welcome
    - script.selfie
    - switch.lupe
  selfies:
    name: Selfies Center
    entities:
    - switch.preview
    - switch.latest
    - switch.loop
  technical:
    name: Technical Center
    entities:
    - script.help



